# Generated by Django 6.0.2 on 2026-02-26 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Video title', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Video description and learning objectives')),
                ('youtube_url', models.URLField(help_text='YouTube video URL (e.g., https://www.youtube.com/watch?v=VIDEO_ID)')),
                ('youtube_embed_url', models.URLField(blank=True, help_text='Auto-generated YouTube embed URL')),
                ('thumbnail_url', models.URLField(blank=True, help_text='YouTube thumbnail URL (auto-generated)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the video is active and can be assigned')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='Admin who added this video', limit_choices_to={'role': 'ADMIN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_videos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VideoAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, help_text="Therapist's notes for this assignment")),
                ('assigned_at', models.DateTimeField(auto_now_add=True, help_text='When the video was assigned')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this assignment is currently active')),
                ('viewed', models.BooleanField(default=False, help_text='Whether the patient has viewed the video')),
                ('viewed_at', models.DateTimeField(blank=True, help_text='When the patient first viewed the video', null=True)),
                ('patient', models.ForeignKey(help_text='Patient receiving the video assignment', limit_choices_to={'role': 'PATIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='video_assignments_received', to=settings.AUTH_USER_MODEL)),
                ('therapist', models.ForeignKey(help_text='Therapist who assigned the video', limit_choices_to={'role': 'THERAPIST'}, on_delete=django.db.models.deletion.CASCADE, related_name='video_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(help_text='Assigned video', on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='videos.video')),
            ],
            options={
                'verbose_name': 'Video Assignment',
                'verbose_name_plural': 'Video Assignments',
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['is_active'], name='videos_vide_is_acti_dd8033_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['-created_at'], name='videos_vide_created_1f1e45_idx'),
        ),
        migrations.AddIndex(
            model_name='videoassignment',
            index=models.Index(fields=['therapist', 'is_active'], name='videos_vide_therapi_0785ff_idx'),
        ),
        migrations.AddIndex(
            model_name='videoassignment',
            index=models.Index(fields=['patient', 'is_active'], name='videos_vide_patient_64d458_idx'),
        ),
        migrations.AddIndex(
            model_name='videoassignment',
            index=models.Index(fields=['-assigned_at'], name='videos_vide_assigne_d127db_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='videoassignment',
            unique_together={('video', 'patient', 'therapist')},
        ),
    ]
