# Generated by Django 6.0.2 on 2026-04-02 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_videoassignment_pause_between_repeats_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoassignment',
            name='schedule_duration_days',
            field=models.PositiveIntegerField(blank=True, help_text='How many consecutive days the patient should watch this video', null=True),
        ),
        migrations.AddField(
            model_name='videoassignment',
            name='schedule_start_date',
            field=models.DateField(blank=True, help_text='First date the video becomes available to the patient', null=True),
        ),
        migrations.AddField(
            model_name='videoassignment',
            name='scheduled_time',
            field=models.TimeField(blank=True, help_text='Daily time (in HH:MM) from which the video unlocks each day', null=True),
        ),
        migrations.AlterField(
            model_name='videoassignment',
            name='viewed',
            field=models.BooleanField(default=False, help_text='Whether the patient has viewed the video at least once (any day)'),
        ),
        migrations.CreateModel(
            name='DailyVideoLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField(help_text='The calendar date this log entry represents')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('VIEWED', 'Viewed'), ('MISSED', 'Missed')], default='PENDING', help_text='Whether the patient viewed the video on this date', max_length=10)),
                ('viewed', models.BooleanField(default=False, help_text='Quick flag: did the patient view on this date?')),
                ('viewed_at', models.DateTimeField(blank=True, help_text='Exact datetime when the patient viewed the video on this date', null=True)),
                ('assignment', models.ForeignKey(help_text='The video assignment this log belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to='videos.videoassignment')),
            ],
            options={
                'verbose_name': 'Daily Video Log',
                'verbose_name_plural': 'Daily Video Logs',
                'ordering': ['scheduled_date'],
                'indexes': [models.Index(fields=['assignment', 'scheduled_date'], name='videos_dail_assignm_191ea1_idx')],
                'unique_together': {('assignment', 'scheduled_date')},
            },
        ),
    ]
