# Generated by Django 6.0.2 on 2026-05-29 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_dailyvideolog_difficulty_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyvideolog',
            name='unlock_email_sent_at',
            field=models.DateTimeField(blank=True, help_text='When the daily unlock email was sent for this date', null=True),
        ),
    ]
