# Generated by Django 5.2.9 on 2026-01-04 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('PATIENT', 'Patient'), ('THERAPIST', 'Therapist')], help_text='Designates the role of the user in the system.', max_length=20),
        ),
    ]
