# Generated by Django 5.2.9 on 2026-01-27 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_therapist_approved',
            field=models.BooleanField(default=False, help_text='Convenience flag indicating therapist is approved'),
        ),
        migrations.AddField(
            model_name='user',
            name='therapist_status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], help_text='Approval status for therapist accounts', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='therapist_verified_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when therapist was approved by admin', null=True),
        ),
    ]
