# Generated by Django 6.0.2 on 2026-05-09 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_backfill_profile_picture_blob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('PATIENT', 'Patient'), ('THERAPIST', 'Therapist'), ('NURSE', 'Nurse')], help_text='Designates the role of the user in the system.', max_length=20),
        ),
    ]
