# Generated by Django 6.0.2 on 2026-05-23 00:00

from django.db import migrations, models
from django.utils import timezone


def mark_existing_users_verified(apps, schema_editor):
    User = apps.get_model("account", "User")
    now = timezone.now()
    for user in User.objects.all():
        if not user.is_email_verified:
            user.is_email_verified = True
            user.email_verified_at = user.email_verified_at or user.created_at or now
            user.save(update_fields=["is_email_verified", "email_verified_at"])


def unmark_existing_users_verified(apps, schema_editor):
    User = apps.get_model("account", "User")
    User.objects.update(is_email_verified=False, email_verified_at=None)


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0006_alter_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="is_email_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(mark_existing_users_verified, unmark_existing_users_verified),
    ]