# Generated by Django 5.2.9 on 2026-01-04 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('past_injuries', models.TextField(blank=True, help_text='Details of any past injuries')),
                ('chronic_conditions', models.TextField(blank=True, help_text='Chronic conditions such as arthritis, asthma, etc.')),
                ('surgeries', models.TextField(blank=True, help_text='Past surgical history')),
                ('medications', models.TextField(blank=True, help_text='Current medications')),
                ('allergies', models.TextField(blank=True, help_text='Known allergies')),
                ('current_symptoms', models.TextField(blank=True, help_text='Current symptoms experienced by the patient')),
                ('medical_report', models.FileField(blank=True, help_text='Optional medical report (PDF)', null=True, upload_to='medical_reports/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Medical History',
                'verbose_name_plural': 'Medical Histories',
            },
        ),
        migrations.CreateModel(
            name='TherapistPatientAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, help_text='Indicates if the assignment is currently active')),
                ('patient', models.ForeignKey(limit_choices_to={'role': 'PATIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_therapists', to=settings.AUTH_USER_MODEL)),
                ('therapist', models.ForeignKey(limit_choices_to={'role': 'THERAPIST'}, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_patients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Therapist-Patient Assignment',
                'verbose_name_plural': 'Therapist-Patient Assignments',
                'unique_together': {('therapist', 'patient')},
            },
        ),
    ]
