# Generated by Django 6.0.2 on 2026-05-09 17:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalhistory',
            name='created_by_nurse',
            field=models.ForeignKey(blank=True, help_text='Nurse who created this medical history record', limit_choices_to={'role': 'NURSE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_histories_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='updated_by_nurse',
            field=models.ForeignKey(blank=True, help_text='Nurse who last updated this medical history record', limit_choices_to={'role': 'NURSE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_histories_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('appointment_type', models.CharField(choices=[('NURSE_CHECKIN', 'Nurse Check-in'), ('THERAPY', 'Therapy'), ('MEDICAL_HISTORY', 'Medical History'), ('FOLLOW_UP', 'Follow-up'), ('OTHER', 'Other')], default='NURSE_CHECKIN', max_length=30)),
                ('scheduled_for', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField(default=30)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('CONFIRMED', 'Confirmed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('is_virtual', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments_created', to=settings.AUTH_USER_MODEL)),
                ('nurse', models.ForeignKey(limit_choices_to={'role': 'NURSE'}, on_delete=django.db.models.deletion.CASCADE, related_name='nurse_appointments', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(limit_choices_to={'role': 'PATIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='patient_appointments', to=settings.AUTH_USER_MODEL)),
                ('therapist', models.ForeignKey(blank=True, limit_choices_to={'role': 'THERAPIST'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='therapist_appointments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Appointment',
                'verbose_name_plural': 'Appointments',
                'ordering': ['-scheduled_for', '-created_at'],
                'indexes': [models.Index(fields=['nurse', 'status'], name='medicals_ap_nurse_i_761634_idx'), models.Index(fields=['patient', 'status'], name='medicals_ap_patient_5da70a_idx'), models.Index(fields=['therapist', 'status'], name='medicals_ap_therapi_c5ac23_idx'), models.Index(fields=['scheduled_for'], name='medicals_ap_schedul_c68320_idx')],
            },
        ),
        migrations.CreateModel(
            name='NursePatientAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('nurse', models.ForeignKey(limit_choices_to={'role': 'NURSE'}, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_patients_as_nurse', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(limit_choices_to={'role': 'PATIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_nurses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nurse-Patient Assignment',
                'verbose_name_plural': 'Nurse-Patient Assignments',
                'ordering': ['-assigned_at'],
                'unique_together': {('nurse', 'patient')},
            },
        ),
    ]
