# Generated by Django 6.0.2 on 2026-05-23 07:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicals', '0002_medicalhistory_created_by_nurse_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(blank=True, help_text='Optional doctor assigned to this appointment', limit_choices_to={'role': 'DOCTOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_appointments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('CONFIRMED', 'Confirmed'), ('COMPLETED', 'Completed'), ('CHECKED_IN', 'Checked-in'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20),
        ),
        migrations.CreateModel(
            name='NursingNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_type', models.CharField(choices=[('NOTE', 'Note'), ('FOLLOW_UP', 'Follow-up'), ('INSTRUCTION', 'Instruction')], default='NOTE', max_length=20)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nursing_notes', to='medicals.appointment')),
                ('nurse', models.ForeignKey(blank=True, limit_choices_to={'role': 'NURSE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nursing_notes_created', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nursing_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nursing Note',
                'verbose_name_plural': 'Nursing Notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vitals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('systolic', models.PositiveIntegerField(blank=True, null=True)),
                ('diastolic', models.PositiveIntegerField(blank=True, null=True)),
                ('temperature_c', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('pulse', models.PositiveIntegerField(blank=True, null=True)),
                ('respiration_rate', models.PositiveIntegerField(blank=True, null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('nurse', models.ForeignKey(blank=True, limit_choices_to={'role': 'NURSE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_vitals', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vitals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vitals',
                'verbose_name_plural': 'Vitals',
                'ordering': ['-recorded_at'],
            },
        ),
    ]
