# Generated by Django 5.2.9 on 2026-01-27 18:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Exercise name', max_length=200)),
                ('description', models.TextField(help_text='Detailed description of the exercise')),
                ('target_area', models.CharField(help_text='Target body area (e.g., Lower Back, Knee, Shoulder)', max_length=100)),
                ('difficulty', models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], default='MEDIUM', help_text='Exercise difficulty level', max_length=10)),
                ('video_file', models.FileField(blank=True, help_text='Upload video file (optional if YouTube URL provided)', null=True, upload_to='exercises/videos/')),
                ('youtube_url', models.URLField(blank=True, help_text='YouTube video URL (optional if video file uploaded)', null=True)),
                ('thumbnail', models.ImageField(blank=True, help_text='Exercise thumbnail image', null=True, upload_to='exercises/thumbnails/')),
                ('instructions', models.TextField(blank=True, help_text='Step-by-step instructions for performing the exercise')),
                ('safety_notes', models.TextField(blank=True, help_text='Safety precautions and contraindications')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the exercise is active/visible')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='Therapist who created this exercise', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_exercises', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Exercise',
                'verbose_name_plural': 'Exercises',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['target_area'], name='exercises_e_target__7fa2f9_idx'), models.Index(fields=['difficulty'], name='exercises_e_difficu_1e38ee_idx'), models.Index(fields=['is_active'], name='exercises_e_is_acti_763092_idx')],
            },
        ),
    ]
