# Generated by Django 5.2.9 on 2026-01-28 03:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExercisePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_duration', models.PositiveIntegerField(default=60, help_text='Duration for performing the exercise in seconds')),
                ('rest_duration', models.PositiveIntegerField(default=20, help_text='Rest duration between sets in seconds')),
                ('sets', models.PositiveIntegerField(default=3, help_text='Number of sets to perform', validators=[django.core.validators.MinValueValidator(1)])),
                ('special_instructions', models.TextField(blank=True, help_text='Special instructions for this patient (e.g., maintain posture)')),
                ('assigned_date', models.DateField(auto_now_add=True, help_text='Date when exercise was assigned')),
                ('scheduled_date', models.DateField(help_text='Date when the exercise should be performed')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this plan is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exercise', models.ForeignKey(help_text='Exercise in the plan', on_delete=django.db.models.deletion.PROTECT, related_name='assigned_plans', to='exercises.exercise')),
                ('patient', models.ForeignKey(help_text='Patient assigned this exercise plan', limit_choices_to={'role': 'PATIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='exercise_plans', to=settings.AUTH_USER_MODEL)),
                ('therapist', models.ForeignKey(help_text='Therapist who assigned this plan', limit_choices_to={'role': 'THERAPIST'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_exercise_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Exercise Plan',
                'verbose_name_plural': 'Exercise Plans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExerciseSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('SKIPPED', 'Skipped')], default='PENDING', help_text='Current status of the exercise session', max_length=20)),
                ('sets_completed', models.PositiveIntegerField(default=0, help_text='Number of sets actually completed', validators=[django.core.validators.MinValueValidator(0)])),
                ('started_at', models.DateTimeField(blank=True, help_text='When the patient started the exercise', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the patient completed the exercise', null=True)),
                ('notes', models.TextField(blank=True, help_text='Patient notes about the exercise (pain, difficulty, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exercise_plan', models.ForeignKey(help_text='Exercise plan being completed', on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='exercises.exerciseplan')),
            ],
            options={
                'verbose_name': 'Exercise Session',
                'verbose_name_plural': 'Exercise Sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='exerciseplan',
            index=models.Index(fields=['patient', 'scheduled_date'], name='exercises_e_patient_80eae8_idx'),
        ),
        migrations.AddIndex(
            model_name='exerciseplan',
            index=models.Index(fields=['patient', 'is_active'], name='exercises_e_patient_325dec_idx'),
        ),
        migrations.AddIndex(
            model_name='exercisesession',
            index=models.Index(fields=['exercise_plan', 'status'], name='exercises_e_exercis_c2c7c0_idx'),
        ),
        migrations.AddIndex(
            model_name='exercisesession',
            index=models.Index(fields=['exercise_plan', 'completed_at'], name='exercises_e_exercis_e8c239_idx'),
        ),
    ]
