# Generated by Django 6.0.2 on 2026-03-26 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_exerciseplan_exercisesession_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciseplan',
            name='frequency',
            field=models.CharField(choices=[('DAILY', 'Daily'), ('EVERY_OTHER_DAY', 'Every Other Day'), ('THREE_TIMES_WEEK', 'Three Times a Week'), ('WEEKLY', 'Weekly')], default='DAILY', help_text='How often the patient should perform this exercise', max_length=20),
        ),
    ]
